---
title: "Untitled"
output: html_document
date: "2024-06-19"
---

```{r load data}
library(tidyverse)

#load("data/full_data.RData")

attributes(full_data$datetime_posix) # already in correct TZ

subdata <- full_data %>% 
  filter(habitat == "slope") %>% 
  filter(! location %in% c("E_slope", "NW_slope")) %>% 
  #filter every fifth row
   filter(row_number() %% 5 == 1)  %>%
  #create day time factor
  mutate(hour = hour(datetime_posix),
         minutes = minute(datetime_posix), 
         time = hour + minutes/60) %>% 
  #select(-c(hour, minutes)) %>% 
  mutate(daynight = ifelse(time > 5 & time < 17, "day", "night"),
         daynight = factor(daynight)) %>% 
  select(HM, location, habitat, datetime_posix, period, month, daynight, day, hour, time, 
         high_freq_M, lunar_phase8, lunar_illum, temp, wd, ws) %>% 
  mutate(lunar_phase8 = factor(lunar_phase8, levels=c("New", "Waxing crescent", "First quarter", "Waxing gibbous", "Full", "Waning gibbous", "Last quarter", "Waning crescent"))) %>%
  mutate(lunar.n = as.numeric(lunar_phase8)) %>%  # model lunar phase as a conituous variable
  #Some extreme outlier maybe association with boat
  #Remove top quantiles for each group 
  #SW_slope has a lot of outliers....
  group_by(location) %>% 
  group_modify(~ if (.y$location == "SW_slope") filter(.x, between(high_freq_M, quantile(high_freq_M, 0), quantile(high_freq_M, .95))) else filter(.x, between(high_freq_M, quantile(high_freq_M, 0), quantile(high_freq_M, .975)))) %>%
  mutate(stemp = scale(temp), 
         sws = scale(ws), 
         nHFM = (high_freq_M-min(high_freq_M))/(max(high_freq_M)-min(high_freq_M)))

subdata_hf <- subdata
```


```{r eval = FALSE}
ggplot(subdata, aes(x = datetime_posix, y = high_freq_M, col = location)) +
  geom_line()

ggplot(subdata, aes(x = stemp, fill = period)) +
  geom_histogram()+
  facet_wrap(~location)
#there is an interaction between temp and time of year
ggplot(subdata, aes(x = sws, fill = period)) +
  geom_histogram()+
  facet_wrap(~location)
#there is an interaction between temp and time of year

ggplot(subdata, aes(x = high_freq_M, fill = location)) +
  geom_histogram()+
  facet_wrap(~location)

ggplot(subdata, aes(x = high_freq_M, fill = location)) +
  geom_histogram()+
  facet_wrap(~location)
ggplot(subdata, aes(x = nHFM, fill = location)) +
  geom_histogram()+
  facet_wrap(~location)
#Much better distributions... 
```

```{r}
subdata.test <- subdata %>% 
  filter(row_number() %% 9 == 1)  %>%
  filter(datetime_posix <= as.Date("2023-05-15")) 

subdata.partial <- subdata %>% 
  filter(row_number() %% 20 == 1)

subdata.full <- subdata 

ggplot() +
  geom_point(data = subdata.test, aes(y = nHFM, x = datetime_posix), col = "red", alpha = .2) +
  geom_point(data = subdata.partial, aes(y = nHFM, x = datetime_posix), col = "pink", alpha = .2) +
  geom_point(data = subdata.full, aes(y = nHFM, x = datetime_posix), col = "lightblue", alpha = .2) +
  facet_wrap(~location)

#how you subset seems to matter
```


# GAMs ----

```{r}
library(mgcv)      #for GAMs
library(gratia)    #for GAM plots
library(broom)     #for tidy output#
library(emmeans)   #for marginal means etc
library(MuMIn)     #for model selection and AICc
library(tidyverse) #for data wrangling
library(DHARMa)    #for simulated residuals
library(performance) #for residual disagnostics
library(see)        # to visualize residual diagnostics
library(ggpubr)     # to combine final plots
```


# Fit the model

```{r}
gam_Hfreq1a <- gam(high_freq_M ~ s(time, bs = "cc", k = 40) +
                    s(location, bs = "re"), 
                  data = subdata.test, 
                  family = betar(),
                  method = 'REML')

gam_Hfreq1b <- gam(nHFM ~ s(time, bs = "cc", k = 40) +
                    s(location, bs = "re"), 
                  data = subdata.test, 
                  family = betar(),
                  method = 'REML')

simulateResiduals(gam_Hfreq1a,  plot=TRUE)
simulateResiduals(gam_Hfreq1b,  plot=TRUE)
#normalised data improves fit
```


## Fit model to partial data ----

```{r}
gam_Hfreq.partial <- gam(nHFM ~ s(time, bs = "cc", k = 40) +
                    lunar_phase8 +
                    #s(day, bs ="ps", k = 10) + #concurvity - soaks up variance from temp
                    s(stemp, bs ="cr", k = 10) +
                    #s(sws, bs = "cr", k = 10) + #not important
                    s(location, daynight, bs = "re"), 
                  data = subdata.partial, 
                  family = betar(),
                  method = 'REML')

gam_Hfreq.partial2 <- gam(nHFM ~ s(time, bs = "cc", k = 40) +
                    lunar_illum + # linear
                    #s(day, bs ="ps", k = 10) + #concurvity - soaks up variance from temp
                    temp + # linear
                    s(location, daynight, bs = "re"), 
                  data = subdata.partial, 
                  family = betar(),
                  method = 'REML')

AIC(gam_Hfreq.partial, gam_Hfreq.partial2)
```


## Model validation
```{r}
k.check(gam_Hfreq.partial2)
appraise(gam_Hfreq.partial2)
concurvity(gam_Hfreq.partial2)
resids <- simulateResiduals(gam_Hfreq.partial2,  plot=TRUE)
testDispersion(resids)
```
Actually, quite a reasonable model


# Full model
```{r}
gam_Hfreq.full <- gam(nHFM ~ s(time, bs = "cc", k = 40) +
                    s(lunar.n,  bs = "cc", k = 5) +
                    s(stemp, bs ="cr", k=10) +
                    # s(sws, bs = "cr", k = 10) + # not important
                    s(location, daynight, bs = "re"), 
                  data = subdata.full, 
                  family = betar(link = "logit"),
                  method = 'REML')
```


## Model validation
```{r}
k.check(gam_Hfreq.full)
appraise(gam_Hfreq.full)
concurvity(gam_Hfreq.full)
resids <- simulateResiduals(gam_Hfreq.full,  plot=TRUE)
testDispersion(resids)
```
Very reasonable

```{r}
my.gam = gam_Hfreq.full
```


# Partial plots
```{r}
draw(my.gam)
#draw(my.gam, residuals = TRUE)
```


# Model investigation / hypothesis testing {.tabset .tabset-faded}
```{r}
summary(my.gam)
```

Significant wiggliness throughout diurnal cycles, lunar cycles, and temperature changes

# Custom Plotting
``` {r}
sm <- smooth_estimates(my.gam) |>
  add_confint()

x <- subdata.full |>
  add_partial_residuals(my.gam)

names(x)

# Choose colours
library(RColorBrewer)
my_cols <- brewer.pal(n = 4, name = 'Dark2')
my_cols

# set font size:
custom_theme <- theme(
  axis.title = element_text(size = 5.5),
  axis.text = element_text(size = 5),)

# plotting time
p_time_HFM <- 
  sm |>
  filter(.smooth == "s(time)") |>
  ggplot() +
  geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci, x = time),
    fill = my_cols[1], alpha = 0.2) +
  geom_line(aes(x = time, y = .estimate), colour = my_cols[1], lwd = 1) +  
      theme_bw() +
  labs(y = "M in the high freq. band (normalised)", x = "Hour of the Day")+
  scale_x_continuous(breaks = seq(0, 25, by = 2), expand = expansion(add=0))+
  scale_y_continuous(expand = expansion(add=0), limits = c(-2.1, 2.1))+
  custom_theme+
  annotate("text", x = -Inf, y = Inf, label = "D", hjust = -0.5, vjust = 1.5, size = 3, fontface = "bold")

# plotting lunar
p_lunar_HFM <- sm |>
  filter(.smooth == "s(lunar.n)") |>
  ggplot() +
  geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci, x = lunar.n),  
    fill= my_cols[3], alpha = 0.2) +
  geom_line(aes(x = lunar.n, y = .estimate), colour = my_cols[3], lwd = 1.) +
      theme_bw() +
  labs(y = "M in the high freq. band (normalised)", x = "Lunar Phase")+
  scale_x_continuous(breaks = seq(1, 8, by = 1), 
                     limits = c(1, 8), 
                     expand = expansion(add = 0),
                     labels = c("New", "", "Waxing", "", "Full", "", "Waning", "")) +
  scale_y_continuous(expand = expansion(add=0), limits = c(-0.51, 0.51))+
  custom_theme+
  annotate("text", x = -Inf, y = Inf, label = "E", hjust = -0.5, vjust = 1.5, size = 3, fontface = "bold")

# plotting temp
p_temp_HFM <- sm |>
  filter(.smooth == "s(stemp)") |>
  ggplot() +
  geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci, x = stemp), 
    fill = my_cols[2], alpha = 0.2) +
  geom_line(aes(x = stemp, y = .estimate), colour = my_cols[2], lwd = 1) +  
  theme_bw() +
  labs(y = "M in the high freq. band (normalised)", x = "Normalised Sea Temperature (Deg C)")+
  scale_x_continuous(expand = expansion(add=0))+
  scale_y_continuous(expand = expansion(add=0), limits = c(-1.5, 1.5))+
  custom_theme+
  annotate("text", x = -Inf, y = Inf, label = "F", hjust = -0.5, vjust = 1.5, size = 3, fontface = "bold")

# combine low and high freq plots
combo_plot <- ggarrange(p_time_LFM, p_time_HFM, 
                        p_lunar_LFM, p_lunar_HFM,
                        p_current_LFM, p_temp_HFM, 
                           ncol = 2, nrow = 3,
                           heights = c(1, 1, 1),
                           align = "v",
                           font.label = list(size = 7))


ggsave("../Plots/combo_plot_all_freqs.png", combo_plot, width = 20, height = 12, units = "cm")

```